### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by torunar** [Janlli/db-backuper#1]
1. https://github.com/Janlli/db-backuper/blob/master/BackupController.php#L63-L64
Колонка первичного ключа в таблице не обязательно называется `id`. 
Первичный ключ может прирастать неравномерно или иметь пропуски.
Первичный ключ может быть составным или вообще отсутствовать.
1. https://github.com/Janlli/db-backuper/blob/master/BackupController.php#L27
https://github.com/Janlli/db-backuper/blob/master/BackupController.php#L70
https://github.com/Janlli/db-backuper/blob/master/BackupController.php#L115-L116
`redirTime` не пишется в свойства объекта, но работа с ним идет как со свойством.
1. https://github.com/Janlli/db-backuper/blob/master/BackupController.php#L59-L61
Образуется лишняя запятая после списка колонок: 
`INSERT INTO table (col1, col2, col3, col4, ) VALUES`.
Тут можно использовать [implode](https://www.php.net/manual/en/function.implode.php)
1. https://github.com/Janlli/db-backuper/blob/master/BackupController.php#L32
https://github.com/Janlli/db-backuper/blob/master/BackupController.php#L98
https://www.php.net/manual/en/function.array-push.php:
    > Note: If you use array_push() to add one element to the array, it's better to use $array[] = because in that way there is no overhead of calling a function. 
1. https://github.com/Janlli/db-backuper/blob/master/BackupController.php#L60
Не выполняется экранирование названий полей.
Поля, совпадающие со служебными командами, сломают дамп.
1. https://github.com/Janlli/db-backuper/blob/master/BackupController.php#L69
Не выполняется экранирование значений. 
Значения с, например, кавычками сломают итоговый дамп.
1. https://github.com/Janlli/db-backuper/blob/master/BackupController.php#L117
Где-то через 5-10 непрерывных редиректов современные браузеры говорят, что с сайтом что-то не так, и перестают перенаправлять пользователя.
1. https://github.com/Janlli/db-backuper/blob/master/BackupController.php#L34
https://github.com/Janlli/db-backuper/blob/master/BackupController.php#L71
https://github.com/Janlli/db-backuper/blob/master/BackupController.php#L36
Редирект происходит после блокировки таблиц, но перед их разблокировкой.
1. Именование переменных не везде отражает их содержимое:
    * `alldb` содержит имена таблиц, но судя по названию, содержит в себе всю БД;
    * `redCount` содержит количество записанных в дамп записей из таблицы, но судя по названию, как-то связан то ли с красным цветом, то ли с счетчиком редиректов;
    * `attrTable` содержит запросы создания таблиц, но судя по названию, связан с какой-то таблицей атрибутов.
Правильное именование переменных и методов позволяет полностью отказаться от комментариев в коде и делает его самодокументируемым.
1. Код не помешает привести в соответствие PSR-2.

**Comment by Janlli** [comment]
1. Исправлено.
2. Исправлено.
3. Исправлено.
4. Исправлено.
5. Добавлено экранирование.
6. Добавлено экранирование.
7. Исправлено. 
8. Добавил разблокировку перед редиректом.
9. Исправил переменные, удалил комментарии.
10. Перевел код в PSR-2.

** Исправил баг с созданием файла при каждом редиректе.

**Comment by torunar** [comment]
11. Что-то теперь приложение падает при открытии `/index`:
```stacktrace
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined function App\Http\Controllers\mysql_real_escape_string()
```

![image](https://user-images.githubusercontent.com/1062217/63243221-f852ab00-c26a-11e9-9bfe-074bd5b51bb5.png)

**Comment by Janlli** [comment]
Исправлено

**Comment by torunar** [comment]
12. Падает при редиректе:
```stacktrace
ErrorException (E_WARNING)
fopen(backups/backup-2019-08-19 08-44-12.sql): failed to open stream: No such file or directory
```
![image](https://user-images.githubusercontent.com/1062217/63251750-67d29580-c27f-11e9-870d-68fc524e557c.png)

**Comment by Janlli** [comment]
вроде исправил

**Comment by torunar** [comment]
13. После 20 редиректов браузер отказывается редиректиться дальше.
![Screen Shot 2019-08-20 at 14 32 54](https://user-images.githubusercontent.com/1062217/63340573-6e810b80-c358-11e9-9bc9-6ba0226aeec7.png)

**Comment by Janlli** [comment]
Добрый день! К сожалению, не знаю как решить эту проблему.

**Comment by torunar** [comment]
@Janlli, вариант с редиректом через meta refresh пробовал?

**Comment by Janlli** [comment]
Нет, попробую сегодня

**Comment by torunar** [comment]
@Janlli, не взлетело?

**Comment by Janlli** [comment]
Взлетело, но не успел ещё протестировать. Завтра с утра выложу.

**Comment by Janlli** [comment]
Добавил редирект с помощью meta refresh

**Comment by torunar** [comment]
Йей, теперь нормально редиректит, но что-то под конец бэкапа идет не так:
![Screen Shot 2019-08-30 at 16 59 46](https://user-images.githubusercontent.com/1062217/64022619-abfb4b00-cb47-11e9-9144-43bedfbbff87.png)

**Comment by Janlli** [comment]
Добрый день! Исправлено.

**Comment by torunar** [comment]
```php
<?php

namespace App\Http\Controllers;

class BackupController extends Controller
{
    private $execTime;
    private $redirTime;
    private $startTime;
    private $currentTime;
    private $lockString = '';
    private $tables = [];
    private $result = '';
    private $tblNames = [];
    private $createTable;
    private $rcdCount;
    private $tblCount;
    private $maxMemoryScript;
    private $currentUsedMemory;

    const MEMORY_SPAN = 10 * 1024 * 1024;
    const TIME_SPAN = 4;

    public function index()
    {
        ini_set('max_execution_time', 6);

        session_start();
        $this->startTime = time();
        $execTime = ini_get('max_execution_time');
        $memoryLimit = ini_get('memory_limit');
        $this->maxMemoryScript = $this->getMemoryLimit($memoryLimit);
        $this->redirTime = $execTime - self::TIME_SPAN;
        $tab = \DB::select('SHOW TABLES');
        foreach ($tab as $k => $v) {
            $v = (array) $v;
            $v = array_values($v);
            $this->tblNames[] = $v[0];
        }
        $this->lockTables(true);
        $this->backup();
        $this->lockTables(false);
        unset($_SESSION['fileName']);
        unset($_SESSION['tblCount']);
        unset($_SESSION['rcdCount']);
    }
    
    private function backup()
    {
        if (!isset($_SESSION['fileName'])) {
            $_SESSION['fileName'] = 'backup-'.date('Y-m-d H-i-s').'.sql';
        }
        (isset($_SESSION['rcdCount'])) ? $this->rcdCount = $_SESSION['rcdCount'] : $this->rcdCount = 0;
        (isset($_SESSION['tblCount'])) ? $this->tblCount = $_SESSION['tblCount'] : $this->tblCount = 0;
        for ($this->tblCount; $this->tblCount < count($this->tblNames); $this->tblCount++) {
            $this->createTable = \DB::select('SHOW CREATE TABLE '.$this->tblNames[$this->tblCount].'');
            $tblRowCount = \DB::table($this->tblNames[$this->tblCount])->count();
            $str = (array) $this->createTable[0];
            if ($this->rcdCount === 0) {
                $this->result .= $str['Create Table'].";\n";
            }
            $allColumns = \DB::getSchemaBuilder()->getColumnListing($this->tblNames[$this->tblCount]);
            if ($tblRowCount != 0) {
                $this->result .= " \n\n\n INSERT INTO ".'`'.$this->tblNames[$this->tblCount].'` '.'(';
                
                $quotedColumns = [];
                foreach ($allColumns as $column) {
                    $quotedColumns[] = "`{$column}`";
                }
                $this->result .= implode(', ', $quotedColumns);
                
                $this->result .= ')  VALUES ';
                for ($this->rcdCount; $this->rcdCount <= $tblRowCount; $this->rcdCount++) {
                    $inserts = \DB::table($this->tblNames[$this->tblCount])->skip($this->rcdCount)->limit(1)->get()->toArray();
                    $insert = reset($inserts);
                    
                    $quotedValues = [];
                    foreach ($insert as $value) {
                        $quotedValues[] = \DB::connection()->getPdo()->quote($value);
                    }
                    $this->result .= "\n(" . implode(', ', $quotedValues) . "),";

                    $this->currentTime = time();
                    $this->currentUsedMemory = memory_get_usage(false);
                    if ($this->isTimeLimitExceeded()
                        || $this->isMemoryLimitExceeded()
                    ) {
                        $this->result = rtrim($this->result, ',') . ';';
                        $this->lockTables(false);
                        $this->redirect();
                    }
                }
                $this->result = rtrim($this->result, ',') . ';';
            }
            $this->result .= "\n\n\n";
            $this->rcdCount = 0;
        }
        $this->writeResult();
    }

    private function lockTables(bool $lock)
    {
        (true === $lock) ? $this->lockString = 'LOCK TABLES ' : $this->lockString = 'UNLOCK TABLES ';
        $showTables = \DB::select('SHOW TABLES');
        foreach ($showTables as $table) {
            foreach ($table as $key => $value) {
                $this->lockString .= "$value WRITE, ";
                $this->tables[] = $value;
            }
        }
        $this->lockString = rtrim($this->lockString, ', ');
        \DB::raw($this->lockString);
    }

    private function writeResult()
    {   if (!file_exists('backups')) {
            mkdir('backups');
        }
        $resultFile = fopen('backups/'.$_SESSION['fileName'], 'a');
        fwrite($resultFile, $this->result);
        fclose($resultFile);
    }

    private function redirect()
    {
        $this->writeResult();
        $_SESSION['rcdCount'] = $this->rcdCount;
        $_SESSION['tblCount'] = $this->tblCount;
        echo
        "<!DOCTYPE html>
        <html lang=\"en\">
        <head>
          <title>TEST</title>
          <meta charset=\"utf-8\">
          <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
          <meta http-equiv=\"refresh\" content=\"0\">
        </head>
        <body>
          <p>Loading...</p>
        </body>
        </html>";
        exit();
    }

    /**
     * @return int
     */
    protected function getMemoryLimit(string $memoryLimit)
    {
        
        $suffix = strtolower(substr($memoryLimit, -1));
        
        if (is_numeric($memoryLimit)) {
            return (int) $memoryLimit;
        } elseif ($suffix === 'm') {
            return (int) $memoryLimit * 1024 * 1024;
        } elseif ($suffix === 'g') {
            return (int) $memoryLimit * 1024 * 1024 * 1024;
        } elseif ($suffix === 'k') {
            return (int) $memoryLimit * 1024;
        }
    }

    protected function isTimeLimitExceeded()
    {
        if ($this->redirTime < 0) {
            return false;
        }
        
        return $this->redirTime < $this->currentTime - $this->startTime;
    }

    protected function isMemoryLimitExceeded() 
    {
        if ($this->maxMemoryScript == 0) {
            return false;
        }

        return ($this->currentUsedMemory > $this->maxMemoryScript - self::MEMORY_SPAN);
    }

    

}
```
